### ISSUE TITLE
Save not happening on switch from html source view back to rendered html view

### ISSUE THREAD

**Issue by keithmorris** [jamestomasino/note#1]
Hey James,

Small bug. If you enter some text, then switch to HTML source view and ad some HTML code (e.g. add an H1 at the top) then switch back to the rendered view, if you don't do any keypresses and just leave the page, when you come back, your added HTML won't be there. Looks like since the saves are happening on keypress, they button presses aren't triggering a save.

I was going to do a pull request to you but I'm not familiar with your build tools. However, I'm thinking you can use the execCommandCallback which should be triggered on a button press and then inspect the object or command to see if it's the HTML button then trigger a save. 

``` javascript
execCommandCallback: function(obj, command) { … }
```

Or you could just trigger the save on any command. In fact, you could probably just reuse your keyUpHandler function to trigger a save on any command: Something like this (since you're not using the parameters anyway):

``` javascript

    $('#redactor_content').redactor({
        focus: true, 
        keyupCallback: keyUpHandler,
        execCommandCallback: keyUpHandler
    });

```

**Comment by jamestomasino** [comment]
Thanks for the issue, Keith! I'll try adding that in. I'm also going to add in a last-minute-save via onbeforeunload as well. It won't work in Opera, but that might help catch any other strays.

**Comment by jamestomasino** [comment]
Also, in case you are curious, I'm using a bunch of ruby tools for my build process. Everything is documented on it over [here](https://github.com/jamestomasino/sass-boilerplate).

**Comment by jamestomasino** [comment]
`execCommandCallback: keyUpHandler` didn't seem to have the desired effect, but onbeforeunload solved it. I've left `execCommandCallback` binding in place anyway as it might help other unseen problems in the future.
